language: r
dist: bionic
cache: packages

addons:
    apt:
        packages:
            - libmagick++-dev

before_install:
  - Rscript -e 'utils::install.packages(c("Matrix","RcppEigen","lattice","MASS","mgcv","httpuv"))'
