# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
cache: packages
r_binary_packages:
  - devtools
  - roxygen2

after_script:
  - Rscript -e 'devtools::install();devtools::test()'
