language: r
dist: bionic
cache: packages

addons:
    apt:
        packages:
            - libmagick++-dev

before_install:
  - Rscript -e 'utils::install.packages("Matrix")'
  - Rscript -e 'utils::install.packages("RcppEigen")'
  - Rscript -e 'utils::install.packages("lattice")'
  - Rscript -e 'utils::install.packages("MASS")'
  - Rscript -e 'utils::install.packages("mgcv")'
  - Rscript -e 'utils::install.packages("httpuv")'

after_script:
  - Rscript -e 'devtools::install();devtools::test()'
