# Header
language: r
r:
  - 4.0.0
  - 4.0.2
cache:
  packages: true
  directories:
  - $HOME/usr/local

warnings_are_errors: true

stages:
  - name: pre-cache1
  - name: pre-cache2
  - name: test

jobs:
  include:
    - stage: pre-cache1
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
         - export PATH=$PATH:$HOME/usr/local/bin
      install:
         - R -e 'install.packages("remotes");remotes::install_github("natverse/natmanager",dependencies = TRUE)'
      script: true
    - stage: pre-cache2
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
         - export PATH=$PATH:$HOME/usr/local/bin
      install:
         - R -e 'natmanager::install("core")'
      script: true
    - stage: test
      before_install:
         - echo 'options(Ncpus = 2)' >> ~/.Rprofile
         - export PATH=$PATH:$HOME/usr/local/bin

addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libgit2-dev

#env
env:
  global:
    - RGL_USE_NULL=TRUE
