# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
cache: packages

addons:
    apt:
        packages:
            - libmagick++-dev
            - libglu1-mesa-dev

env:
  global:
    - RGL_USE_NULL=TRUE

before_install:
  - Rscript -e 'utils::install.packages("Matrix")'
  - Rscript -e 'utils::install.packages("RcppEigen")'
  - Rscript -e 'utils::install.packages("lattice")'
  - Rscript -e 'utils::install.packages("MASS")'
  - Rscript -e 'utils::install.packages("mgcv")'
  - Rscript -e 'utils::install.packages("httpuv")'

after_script:
  - Rscript -e 'devtools::install();devtools::test()'
