# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os:
  - linux
addons:
  apt:
    packages:
    - libglu1-mesa-dev
    - libmagick++-dev
    - gfortran
env:
  global:
    - RGL_USE_NULL=TRUE
jobs:
  include:
    - stage: prepare cache
      script: true
    - stage: test
before_install:
  - echo 'options(Ncpus = 2)' >> ~/.Rprofile
