# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
dist: bionic
cache: packages
r_binary_packages:
  - devtools
  - roxygen2
  - rcppeigen
  - rcpp
  - matrix

addons:
    apt:
        packages:
            - libmagick++-dev

before_install:
  - Rscript -e 'utils::install.packages("Matrix")'
  - Rscript -e 'utils::install.packages("RcppEigen")'
  - Rscript -e 'utils::install.packages("lattice")'
  - Rscript -e 'utils::install.packages("MASS")'
  - Rscript -e 'utils::install.packages("mgcv")'
  - Rscript -e 'utils::install.packages("httpuv")'

after_script:
  - Rscript -e 'devtools::install();devtools::test()'
